Automation-Changes-A
AbstractXan/LINK_PUMP pull request #6
Opened 2020-12-20 12:20 UTC by RealRadOne

2020-12-20 12:42 UTC, AbstractXan requested changes
Works great. We might have to edit Mizi's hard coded config to get all our data appropriately.

2020-12-20 12:42 UTC, AbstractXan commented on src/client.py
> +outCSV = open("out.csv","w")
This should be renamed to `data.csv` since LINK_PUMP reads looks for `data.csv`

2020-12-20 12:42 UTC, AbstractXan commented on src/build.sh
> +python3 client.py
Might wanna rename to something better

2020-12-20 12:42 UTC, AbstractXan commented on src/client.py
> +api_hash = '36722c72256a24c1225de00eb6a1ca74'
You sure you wanna put this out to public ?

2020-12-20 12:52 UTC, RealRadOne commented on src/client.py
> +api_hash = '36722c72256a24c1225de00eb6a1ca74'
Yes,they are telegram public api keys

2020-12-20 13:19 UTC, AbstractXan requested changes
We don't wanna lose `src/data.csv`

2020-12-21 02:00 UTC, RealRadOne commented
> We don't wanna lose `src/data.csv`

2020-12-21 03:41 UTC, AbstractXan approved these changes

2020-12-21 03:42 UTC, AbstractXan approved these changes

2020-12-21 03:55 UTC, AbstractXan commented
The changes seem correct. However the Netlify builds are not working right. Merging this PR and fixing this on master.

2020-12-21 03:55 UTC, merged

2020-12-21 04:30 UTC, siddish-reddy commented on src/extparse.py
> +api_hash = '36722c72256a24c1225de00eb6a1ca74'
let's shift this to env variable if it has read and also write authorization

2020-12-21 05:59 UTC, AbstractXan commented on src/extparse.py
> +api_hash = '36722c72256a24c1225de00eb6a1ca74'
Yeah I asked @RealRadOne if she was okay with this -- she said yes.